name: Deploy to Hugging Face Space
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        env:
          MKFLASHCARDS_TOKEN: ${{ secrets.MKFLASHCARDS_TOKEN }}
        run: git push -f https://intellectronica:$MKFLASHCARDS_TOKEN@huggingface.co/spaces/intellectronica/mkflashcards main
