name: Lint with Ruff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run Ruff
      id: run_ruff
      run: |
        uv run ruff check . > ruff_output.txt || true
        cat ruff_output.txt

    - name: Create PR Comment
      if: always()
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Ruff
          ```
          ${{ steps.run_ruff.outputs.stdout }}
          ```
